services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-management-server
    env_file:
      - ./.env
    ports:
      - '3770:3770'
    volumes:
      - ./src:/app/src