services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-management-client
    env_file:
      - ./.env.local
    ports:
      - '3775:3775'
    volumes:
      - ./src:/app/src